services:
  postgres:
    image: postgres:15
    container_name: flight_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flights_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  postgres_data:
